# Generated by Django 3.1.8 on 2021-05-28 09:48

from django.db import migrations
import vigolend.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210521_1506'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', vigolend.users.models.UserManager()),
            ],
        ),
    ]
