# Generated by Django 3.1.8 on 2021-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210528_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('current', 'Current Address'), ('permanent', 'Permanent Address')], default='current', help_text='The type of address.', max_length=9, verbose_name='Address Type'),
        ),
    ]
