# Generated by Django 3.1.8 on 2021-05-28 13:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.', verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=20, verbose_name='name')),
                ('designation', models.CharField(help_text='The position of the team member.', max_length=50, verbose_name='Designation')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', max_length=50, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(help_text='Twitter handle- without `@`.', max_length=50, verbose_name='Twitter Handle')),
                ('photo', models.ImageField(help_text='The photo of the team member.', upload_to='team', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
