# Generated by Django 3.1.8 on 2021-05-28 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English name of country', max_length=255, verbose_name='Country Name')),
                ('phone_code', models.CharField(blank=True, help_text='Countries International dialing phone code.', max_length=100, null=True, verbose_name='Phone Code')),
                ('currency', models.CharField(blank=True, help_text='Official country currency.', max_length=50, null=True, verbose_name='Currency')),
                ('iso2', models.CharField(blank=True, help_text='Two-letter country code', max_length=2, null=True, verbose_name='ISO2')),
                ('native', models.CharField(blank=True, help_text='Localized or native language of country.', max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created', verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date')),
                ('accept_signup', models.BooleanField(default=True, help_text='Allow users from country to register.', verbose_name='Accept Registration')),
                ('banned', models.BooleanField(default=False, help_text='Indicate if country is banned or not', verbose_name='Banned')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the State or Region.', max_length=255, verbose_name='State Name')),
                ('country_code', models.CharField(blank=True, help_text='The ISO 4217 code of the Country.', max_length=2, verbose_name='Country Code')),
                ('iso2', models.CharField(blank=True, help_text='Two-letter state code', max_length=255, null=True, verbose_name='ISO2')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created', verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date')),
                ('country', models.ForeignKey(help_text='Name of the country of the State or Provinces.', on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'State / Region',
                'verbose_name_plural': 'States & Regions',
                'db_table': 'state_regions',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' The name of the city location.', max_length=255, verbose_name='City Name')),
                ('country_code', models.CharField(blank=True, max_length=5, verbose_name='Country Code')),
                ('state_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='State Code')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.', verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date')),
                ('country', models.ForeignKey(help_text='Name of the country of the State or Provinces.', on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country Name')),
                ('state', models.ForeignKey(help_text='The name of the State or Provinces. Identifies a subdivision of a country such as state, region, county.', on_delete=django.db.models.deletion.PROTECT, to='locations.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'City Location',
                'verbose_name_plural': 'City Locations',
                'db_table': 'city_locations',
            },
        ),
    ]
